/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x40, 0x13, 0xA0, 0xCD, 0x14, 0x2B, 0xB5, 0xB0}

#define VIAL_UNLOCK_COMBO_ROWS { 2, 3 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 0 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 5
#define DYNAMIC_KEYMAP_COMBO_COUNT 2
#define DYNAMIC_KEYMAP_MACRO_COUNT 2
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4